### 获取所有服务实例
GET http://localhost:8484/findAll?service=cn.lokn.knrpc.demo.api.UserService

### 注册一个实例
POST http://localhost:8484/reg?service=cn.lokn.knrpc.demo.api.UserService
Content-Type: application/json

{
  "schema" : "http",
  "context": "knrpc",
  "host": "127.0.0.1",
  "port": 8082,
  "status": false,
  "parameters": {
    "evn": "dev",
    "tag": "RED"
  }
}

### 取消实例
POST http://localhost:8484/unreg?service=cn.lokn.knrpc.demo.api.UserService
Content-Type: application/json

{
  "schema" : "http",
  "context": "knrpc",
  "host": "127.0.0.1",
  "port": 8082
}

### 刷新服务时间戳
POST http://localhost:8484/renew?service=cn.lokn.knrpc.demo.api.UserService
Content-Type: application/json

{
  "schema" : "http",
  "context": "knrpc",
  "host": "127.0.0.1",
  "port": 8082
}

### 探活服务
POST http://localhost:8484/renews?service=cn.lokn.knrpc.demo.api.UserService
Content-Type: application/json

{
  "schema" : "http",
  "context": "knrpc",
  "host": "127.0.0.1",
  "port": 8082
}

### 获取版本号
POST http://localhost:8484/version?service=cn.lokn.knrpc.demo.api.UserService

### 获取当前实例
GET http://localhost:8484/info

### 获取leader
GET http://localhost:8484/leader